import type { Workflow, Execution, DashboardStats, ChartData } from "./types"

// 🎯 DATOS REALISTAS - Simulan lo que vendría de N8N + Python
export const mockWorkflows: Workflow[] = [
  {
    id: "wf-001",
    name: "E-commerce Order Processing",
    description: "Automatiza el procesamiento de pedidos desde Shopify hasta el sistema de inventario",
    status: "active",
    lastExecution: new Date("2024-01-30T14:30:00"),
    totalExecutions: 1247,
    successRate: 98.5,
    avgExecutionTime: 2340, // ms
    timeSavedHours: 156.2,
    category: "E-commerce",
    triggers: ["Shopify Webhook", "Schedule"],
    actions: ["Update Inventory", "Send Email", "Create Invoice"],
  },
  {
    id: "wf-002",
    name: "Lead Qualification System",
    description: "Califica leads automáticamente y los asigna al equipo de ventas apropiado",
    status: "active",
    lastExecution: new Date("2024-01-30T15:45:00"),
    totalExecutions: 892,
    successRate: 96.8,
    avgExecutionTime: 1890,
    timeSavedHours: 89.3,
    category: "Sales",
    triggers: ["Form Submission", "CRM Update"],
    actions: ["Score Lead", "Assign Sales Rep", "Send Notification"],
  },
  {
    id: "wf-003",
    name: "Social Media Content Sync",
    description: "Sincroniza contenido entre múltiples plataformas sociales",
    status: "error",
    lastExecution: new Date("2024-01-30T12:15:00"),
    totalExecutions: 445,
    successRate: 94.2,
    avgExecutionTime: 3200,
    timeSavedHours: 67.8,
    category: "Marketing",
    triggers: ["Content Published", "Schedule"],
    actions: ["Post to Twitter", "Post to LinkedIn", "Update Analytics"],
  },
  {
    id: "wf-004",
    name: "Customer Support Ticket Routing",
    description: "Enruta tickets de soporte automáticamente basado en prioridad y expertise",
    status: "active",
    lastExecution: new Date("2024-01-30T16:20:00"),
    totalExecutions: 2156,
    successRate: 99.1,
    avgExecutionTime: 1200,
    timeSavedHours: 234.7,
    category: "Support",
    triggers: ["Ticket Created", "Priority Change"],
    actions: ["Categorize Ticket", "Assign Agent", "Set Priority"],
  },
  {
    id: "wf-005",
    name: "Financial Report Generation",
    description: "Genera reportes financieros automáticos y los envía a stakeholders",
    status: "inactive",
    lastExecution: new Date("2024-01-29T09:00:00"),
    totalExecutions: 156,
    successRate: 100,
    avgExecutionTime: 8900,
    timeSavedHours: 78.4,
    category: "Finance",
    triggers: ["Schedule"],
    actions: ["Generate Report", "Send Email", "Update Dashboard"],
  },
]

export const mockExecutions: Execution[] = [
  {
    id: "exec-001",
    workflowId: "wf-001",
    workflowName: "E-commerce Order Processing",
    status: "success",
    startTime: new Date("2024-01-30T16:30:00"),
    endTime: new Date("2024-01-30T16:30:02"),
    duration: 2340,
    dataProcessed: 15,
    triggeredBy: "Shopify Webhook",
  },
  {
    id: "exec-002",
    workflowId: "wf-002",
    workflowName: "Lead Qualification System",
    status: "success",
    startTime: new Date("2024-01-30T16:25:00"),
    endTime: new Date("2024-01-30T16:25:01"),
    duration: 1890,
    dataProcessed: 3,
    triggeredBy: "Form Submission",
  },
  {
    id: "exec-003",
    workflowId: "wf-003",
    workflowName: "Social Media Content Sync",
    status: "error",
    startTime: new Date("2024-01-30T16:15:00"),
    endTime: new Date("2024-01-30T16:15:05"),
    duration: 5000,
    errorMessage: "Twitter API rate limit exceeded",
    dataProcessed: 0,
    triggeredBy: "Content Published",
  },
  {
    id: "exec-004",
    workflowId: "wf-004",
    workflowName: "Customer Support Ticket Routing",
    status: "success",
    startTime: new Date("2024-01-30T16:20:00"),
    endTime: new Date("2024-01-30T16:20:01"),
    duration: 1200,
    dataProcessed: 8,
    triggeredBy: "Ticket Created",
  },
  {
    id: "exec-005",
    workflowId: "wf-001",
    workflowName: "E-commerce Order Processing",
    status: "running",
    startTime: new Date("2024-01-30T16:35:00"),
    dataProcessed: 0,
    triggeredBy: "Schedule",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalWorkflows: 5,
  activeWorkflows: 3,
  totalExecutions: 4896,
  successRate: 97.8,
  totalTimeSaved: 626.4,
  totalROI: 15660, // $25/hour * 626.4 hours
  executionsToday: 47,
  errorsToday: 2,
}

export const mockChartData: ChartData[] = [
  { date: "2024-01-24", executions: 45, successes: 44, errors: 1, timeSaved: 12.3 },
  { date: "2024-01-25", executions: 52, successes: 50, errors: 2, timeSaved: 14.1 },
  { date: "2024-01-26", executions: 38, successes: 37, errors: 1, timeSaved: 10.8 },
  { date: "2024-01-27", executions: 61, successes: 59, errors: 2, timeSaved: 16.7 },
  { date: "2024-01-28", executions: 43, successes: 42, errors: 1, timeSaved: 11.9 },
  { date: "2024-01-29", executions: 55, successes: 53, errors: 2, timeSaved: 15.2 },
  { date: "2024-01-30", executions: 47, successes: 45, errors: 2, timeSaved: 13.4 },
]